
spring.datasource:
  driverClassName: org.h2.Driver
  url: "jdbc:h2:mem:db;mode=Oracle;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=category,key,value;INIT=RUNSCRIPT FROM 'classpath:sql/schema/init.sql'"

spring.h2:
  console:
    enabled: true
    path: /app-h2-console
